Noticias/Controllers/RotasController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using Noticias.Models;

namespace Noticias.Controllers
{
    public class RotasController : Controller
    {
        // GET: Rotas
        private readonly IEnumerable<Noticia> todasAsNoticias;

        public RotasController()
        {
            todasAsNoticias = new Noticia().TodasAsNoticias().OrderByDescending(x => x.Data);
        }

        public ActionResult Index()
        {
            var ultimasNoticias = todasAsNoticias.Take(3);
            var todasAsCategorias = todasAsNoticias.Select(x => x.Categoria).Distinct().ToList();


            ViewBag.Categorias = todasAsCategorias;
            return View(ultimasNoticias);
        }

        public ActionResult TodasAsNoticias()
        {
            return View(todasAsNoticias);
        }

        public ActionResult MostraNoticia(int noticiaId, string titulo, string categoria)
        {
            return View(todasAsNoticias.FirstOrDefault(x => x.NoticiaId == noticiaId));
        } 

        public ActionResult MostraCategoria(string categoria)
        {
            var categoriaEspecifica = todasAsNoticias.Where(x => x.Categoria.ToLower() == categoria.ToLower()).ToList();
            ViewBag.categoria = categoria;
            return View(categoriaEspecifica);
        }
    }
}

Noticias/Views/Rotas/Index.cshtml
@model IEnumerable<Noticias.Models.Noticia>

@{
    ViewBag.Title = "Index";
}

<h2>Rotas em ASP</h2>

<div>
    <ul>
        @foreach(string item in ViewBag.Categorias)
        {
            <li>
                @Html.ActionLink(item, "MostraCategoria", "Rotas", new { @categoria = item}, null)
            </li>
        }
    </ul>
</div>

<div>
    <ul>
        @foreach(var item in Model)
        {
            <li>
                @Html.ActionLink(item.Titulo, "MostraNoticia", "Rotas", new{
                @noticiaId = item.NoticiaId,
                @categoria = item.Categoria.ToLower(),
                @titulo = item.Titulo.ToLower()
                
                }, null);
                <em>@Html.DisplayFor(modelItem => item.Categoria)</em>
                <b>@Html.DisplayFor(modelItem => item.Data)</b>
            </li>
        }
    </ul>
</div>

<div>
    @Html.ActionLink("Todas as Notivias", "TodasAsNoticias", "Rotas");
</div>

Noticias/Views/Rotas/MostraCategoria.cshtml
@model IEnumerable<Noticias.Models.Noticia>
@{
    ViewBag.Title = "Categoria";
}

<h2>Categoria: @ViewBag.Categoria</h2>
<div>
    <ul>
        @foreach (var item in Model)
        {
            <li>
                @Html.ActionLink(item.Titulo, "MostraNoticia", "Rotas", new
           {
               @noticiaId = item.NoticiaId,
               @categoria = item.Categoria.ToLower(),
               @titulo = item.Titulo.ToLower()

           }, null);
                <em>@Html.DisplayFor(modelItem => item.Categoria)</em>
                <b>@Html.DisplayFor(modelItem => item.Data)</b>
            </li>
        }
    </ul>
</div>

Noticias/Views/Rotas/MostraNoticia.cshtml
@model Noticias.Models.Noticia
@{
    ViewBag.Title = "MostraNoticia";
}

<h2>@Model.Titulo</h2>
<em>@Model.Data - @Html.ActionLink(@Model.Categoria, "MostraCategoria", "Rotas", new { @categoria = Model.Categoria}, null)</em>

<div>@Model.Conteudo</div>

Noticias/Views/Rotas/TodasAsNoticias.cshtml
@model IEnumerable<Noticias.Models.Noticia>
@{
    ViewBag.Title = "TodasAsNoticias";
}

<h2>Todas As Noticias</h2>
<div>
    <ul>
        @foreach(var item in Model)
        {
            <li>
                @Html.ActionLink(item.Titulo, "MostraNoticia", "Rotas", new{
                @noticiaId = item.NoticiaId,
                @categoria = item.Categoria.ToLower(),
                @titulo = item.Titulo.ToLower()
                
                }, null);
                <em>@Html.DisplayFor(modelItem => item.Categoria)</em>
                <b>@Html.DisplayFor(modelItem => item.Data)</b>
            </li>
        }
    </ul>
</div>